### ISSUE TITLE
Modes

### ISSUE THREAD

**Issue by DeaSTL** [cmaker-dev/index#3]
```toml
[project]
authors = []
build_dir = 'build'
cflags = []
cmake_version = '3.10'
compiler = 'g++'
include_dir = 'include'
lang = 'cpp'
lang_version = '20'
project_name = 'DEBUG'
project_version = '0.0.1'
src_dir = 'src'
[mode.debug]
cflags = ['-g']
[mode.debug.dependencies]


[dependencies]

```
add mode support for "mode based" dependecy and flag management so they can do similar testing shit to us
